apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing-page
  namespace: danny-armijos
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/acme-challenge-type: http01
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: dmarmijosa.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: landing-page
            port:
              number: 80
  tls:
  - hosts:
    - dmarmijosa.com
    secretName: landing-page-tls
