apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing-page
  namespace: landing-page
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - host: dmarmijosa.com # ¡Tu dominio!
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: landing-page # Nombre de tu Service
            port:
              number: 3000 # Puerto del Service
  tls:
  - hosts:
    - dmarmijosa.com # ¡Tu dominio!
    secretName: dmarmijosa-tls # ¡Nombre del secreto TLS que creará cert-manager! (Debe coincidir con 05-certificate.yaml)