apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dmarmijosa@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsNames:
        - 'dmarmijosa.com'
      http01:
        ingress:
          class: nginx
          ingressTemplate:
            metadata:
              annotations:
                cert-manager.io/issue-temporary-certificate: "true"
